---
title: "Projects: 2019"
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    includes:
      in_header: 
        - ../style/all_ga_script.html
        - ../style/all_navbar_head.html
        - ../style/all_orange_jp_01_lvl.html
      before_body:
        - ../style/all_navbar_body_01_lvl.html
        - ../style/projects_2019_page_header.html
      after_body:
        - ../style/all_footer_01_lvl.html
    self_contained: FALSE
---

## (Ongoing) `perler` package in Python

This Python package is designed to generate a personal income statement given a ledger that follows a proper format. Details will be written soon.


## (Ongoing) `qgf` package in R

Using `DBI` package, this R package aims to generate SQL queries that perform data tidying and create simple analysis. Details will be written soon.

## `sudsoln` package in Python

To get familiar with object-oriented programming in Python, I created a package that solves a $n^2$-by-$n^2$ sudoku puzzle, where $n$ is the number of rows/columns in a subarray. See [here](2019/sudsoln.html) for details.


## `funpark` package in R

To gain experience in a package development in R, I started to gather and organize R functions I wrote in the [Research materials](research_materials.html) section. See [here](2019/funpark.html) for details.


# Publishing this [website](https://joon3216.github.io)

The challenge was to learn about HTML and CSS to make my website look like a website. Also, I learned some git commands for a better management of files in the [repository](https://github.com/joon3216/joon3216.github.io). See [here](2019/publishing_website.html) for details.





