---
title: "Curriculum Vitae"
author: Junkyu Park
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    includes:
      in_header: 
        - style/all_ga_script.html
        - style/all_navbar_head.html
        - style/all_orange_jp_00_lvl.html
      before_body:
        - style/all_navbar_body_00_lvl.html
      after_body:
        - style/all_footer_00_lvl.html
    toc: FALSE
    toc_depth: 1
    self_contained: FALSE
---


Last updated: May 28, 2019.

<!--html_preserve-->
&nbsp;
<div id="TOC">
<ul>
<li><a href="#contact"><strong>Contact</strong></a></li>
<li><a href="#education"><strong>Education</strong></a></li>
<li><a href="#experience"><strong>Experience</strong></a></li>
<li><a href="#skills"><strong>Skills</strong></a></li>
<li><a href="#awards"><strong>Awards</strong></a></li>
<li><a href="#languages"><strong>Languages</strong></a></li>
</ul>
</div>
<!--/html_preserve-->


# **Contact**

* $($ 647 $)$ 676-4374
* joon3216 [at] gmail [dot] com
* https://linkedin.com/in/asdfzxcvjkl1/
* https://joon3216.github.io/


# **Education**

* **University of Toronto**
    + expected to graduate in June 2019
    + H.B.Sc. in statistics (specialist) and math (minor)


# **Experience**

* **University of Toronto Accessibility Services**
    + Volunteer note-taker
    + Sept 2013 - Apr 2014 and Sept 2016 - Apr 2019 (3 years 4 months)
        + volunteered as a note-taker for students with disabilities

* **The 15^th^ Infantry Division, Republic of Korea Army**
    + Assistant Squad Leader (Sergeant)
    + Oct 2014 - July 2016 (1 year 9 months)
        + Second deployment to the General Outpost in June 2016 until discharged
        + Assistant Squad Leader as of Dec 2015 until discharged (7 months)
        + First deployment to the 38^th^ Regiment's General Outpost from Sept 2015 to Feb 2016 (6 months)


# **Skills**

* Certifications
    + Society of Actuaries
        + Exam accredited: SRM
        + Exams passed: P, FM
        + All VEEs obtained: Economics, Applied Statistics, Corporate Finance
* Programming
    + **PostgreSQL**
        + understand that using capital letters in a column name is a way to maintenance hell
        + able to use functions such as `unnest`, `array`, `information_schema`, etc.
        + able to combine information in tables using:
            + if-then-else statement using `CASE`, `WHEN`, `THEN`, and `ELSE`
            + `INNER JOIN`, `USING`, `LEFT JOIN`, `RIGHT JOIN`, `FULL JOIN`, `CROSS JOIN`
            + `UNION`, `UNION ALL`, `INTERSECT`, `EXCEPT`
        + able to write subqueries
    + **Python**
        + able to write functions to implement algorithms
    + **R**
        + familiar with `ggplot2`, `dplyr`, `dbplyr`, `tidyr`, and `purrr`
        + able to write functions to implement algorithms



# **Awards**

* Dean's List Scholar, 2013-14, 2016-17, 2017-18
* Louis Salvov Scholarship, 2016-17
* Awards for Excellence in Army Training Test, May 2016
* Math Honour Roll, June 2014
* University of Toronto AccessAbility Certificate of Appreciation, Apr 2014
* University of Toronto Entrance Scholarship, Sept 2013


# **Languages**

* English, Korean







