---
title: "Projects"
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    includes:
      in_header: 
        - style/all_ga_script.html
        - style/all_navbar_head.html
        - style/all_orange_jp_00_lvl.html
      before_body:
        - style/all_navbar_body_00_lvl.html
        - style/projects_page_header.html
      after_body:
        - style/all_footer_00_lvl.html
    self_contained: FALSE
---


# [2019](projects/2019.html)

<!-- ## (Ongoing) `perler` package in Python -->

<!-- This Python package is designed to generate a personal income statement given a ledger that follows a proper format. Details will be written soon. -->


<!-- ## (Ongoing) `qgf` package in R -->

<!-- Using `DBI` package, this R package aims to generate SQL queries that perform data tidying and create simple analysis. Details will be written soon. -->

## Credit card fraud detection

To gain skills in using and exploring Python external packages such as `matplotlib.pyplot`, `seaborn`, `pandas`, `statsmodels.api` and so forth, I finished a project related to supervised learning.

* [Description](projects/2019/creditcardfraud.html)
* [Analysis](projects/2019/creditcardfraud/analysis.html)


## `sudsoln` package in Python

To get familiar with object-oriented programming in Python, I created a package that solves a $n^2$-by-$n^2$ sudoku puzzle, where $n$ is the number of rows/columns in a subarray. 

* [Description](projects/2019/sudsoln.html)
* [Repository](https://github.com/joon3216/sudsoln)
* [Introduction to `sudsoln`](projects/2019/sudsoln/introduction.html)
* [Analysis](projects/2019/sudsoln/analysis.html)

## `funpark` package in R

To gain experience in a package development in R, I started to gather and organize R functions I wrote in the [Research materials](research_materials.html) section. 

* [Description](projects/2019/funpark.html)
* [Repository](https://github.com/joon3216/funpark)


## Publishing this [website](https://joon3216.github.io)

The challenge was to learn about HTML and CSS to make my website look like a website. Also, I learned some git commands for a better management of files in the [repository](https://github.com/joon3216/joon3216.github.io). 

* [Description](projects/2019/publishing_website.html)
* [Repository](https://github.com/joon3216/joon3216.github.io)






<!--html_preserve-->
&nbsp;  
&nbsp;  
&nbsp;  
<!--/html_preserve-->
















<!-- note: (n.d.) stands for "no date" -->

<!--html_preserve-->
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Project [B2]. (n.d.). In the Cambridge English Dictionary. Retrived May 27, 2019, from <a href="https://dictionary.cambridge.org/dictionary/english/project" class="uri">https://dictionary.cambridge.org/dictionary/english/project</a><a href="#fnref1">&uarr;</a></p></li>
</ol>
</div>
<!--/html_preserve-->





