---
title: "News: June 2019"
author: Junkyu Park
date: "Last updated: `r Sys.Date()`"
output: 
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
    includes:
      in_header: 
        - ../style/all_ga_script.html
        - ../style/all_navbar_head.html
        - ../style/all_orange_jp_01_lvl.html
      before_body:
        - ../style/all_navbar_body_01_lvl.html
      after_body:
        - ../style/news_footer_tactile_01_lvl.html
    toc: FALSE
    self_contained: FALSE
---


<!--html_preserve-->
<div class="news_center" style="
    display: block;
    text-align: -webkit-center;
    line-height: 1.6;
    font-family: sans-serif;
    font-size: .875em;
">

<table class="news_table" style="
    display: table;
    font-size: 100%;
    margin: 1em 0;
    background-color: #AAA;
    border: 1px solid #AAA;
    border-collapse: collapse;
    color: black;
    width: 100%;
    table-layout: fixed;
">

<tbody>

<tr>
<th class="table_title"colspan="7" style="text-align: center; text-shadow: none;"><a class="fas fa-angle-left" style="color: rgba(0, 0, 0, 0); font-size: 18pt;"></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a style="font-size: 18pt; color: #FFF;">June 2019</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="fas fa-angle-right" title="2019-07" href="2019-07.html" style="color: #1E6BB8; font-size: 18pt;"></a></th>
</tr>

<tr>
<td style="text-align: center;"><a>Sun</a></td>
<td style="text-align: center;"><a style="color: black;">Mon</a></td>
<td style="text-align: center;"><a style="color: black;">Tue</a></td>
<td style="text-align: center;"><a style="color: black;">Wed</a></td>
<td style="text-align: center;"><a style="color: black;">Thu</a></td>
<td style="text-align: center;"><a style="color: black;">Fri</a></td>
<td style="text-align: center;"><a style="color: darkblue;">Sat</a></td>
</tr>

<tr>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section" style="color: #1E6BB8;">01</a></td>
</tr>

<tr>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-1" style="color: #1E6BB8;">02</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-2" style="color: #1E6BB8;">03</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-3" style="color: #1E6BB8;">04</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-4" style="color: #1E6BB8;">05</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-5" style="color: #1E6BB8;">06</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-6" style="color: #1E6BB8;">07</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-7" style="color: #1E6BB8;">08</a></td>
</tr>

<tr>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-8" style="color: #1E6BB8;">09</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-9" style="color: #1E6BB8;">10</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-10" style="color: #1E6BB8;">11</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-11" style="color: #1E6BB8;">12</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-12" style="color: #1E6BB8;">13</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-13" style="color: #1E6BB8;">14</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-14" style="color: #1E6BB8;">15</a></td>
</tr>

<tr>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-15" style="color: #1E6BB8;">16</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-16" style="color: #1E6BB8;">17</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-17" style="color: #1E6BB8;">18</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-18" style="color: #1E6BB8;">19</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-19" style="color: #1E6BB8;">20</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-20" style="color: #1E6BB8;">21</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-21" style="color: #1E6BB8;">22</a></td>
</tr>

<tr>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-22" style="color: #1E6BB8;">23</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a href="#section-23" style="color: #1E6BB8;">24</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a>25</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a>26</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a>27</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a>28</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a>29</a></td>
</tr>

<tr>
<td style="text-align: center; border: 1px solid #BBB;"><a>30</a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
<td style="text-align: center; border: 1px solid #BBB;"><a> </a></td>
</tr>

</tbody>
</table>
</div>
<!--/html_preserve-->









# 01

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.cbsnews.com/news/liverpool-defeats-tottenham-2-0-in-champions-league-final-today-2019-06-01/">Champions League final: Liverpool defeats Tottenham 2-0</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.cbc.ca/news/canada/montreal/woman-faked-being-nurse-jonquiere-20-years-1.5157101">Quebec woman faked being a nurse for 20 years</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.fromthegrapevine.com/innovation/stephen-hawking-radiation-sonic-black-hole-temperature-jeff-steinhauer">Stephen Hawking's prediction on Hawking Radiation confirmed, thanks to lab-created black hole</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.techspot.com/news/80312-t-series-beats-pewdiepie-race-hit-100-million.html">T-Series beats PewDiePie in race to hit 100 million subscribers</a><!--/html_preserve-->



# 02

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.nytimes.com/2019/06/02/sports/nba-finals-golden-state-warriors-toronto-raptors.html">NBA Finals: Warriors Tie Series with Raptors</a><!--/html_preserve-->



# 03

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.forbes.com/sites/tiriasresearch/2019/06/03/amd-licenses-graphics-technology-to-samsung/#7adf188e6a12">AMD licenses graphics technology to Samsung</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://nationalpost.com/news/canada/report-on-missing-and-murdered-indigenous-women-and-girls-calls-for-significant-change-to-police-services-across-canada">Report on missing, murdered Indigenous women calls for significant change to police services across Canada</a><!--/html_preserve--> 
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://toronto.ctvnews.ca/ttc-s-first-fully-electric-bus-now-in-service-in-the-city-1.4448868">TTC's first fully electric bus now in service in Toronto</a><!--/html_preserve-->


# 04

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.cicnews.com/2019/06/ontario-invites-express-entry-candidates-with-work-experience-in-10-occupations-0612344.html#gs.g98xg2">Ontario invites Express Entry candidates with work experience in 10 occupations</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://phys.org/news/2019-06-machine-sensors.html">Researchers developed AIfES, an artificial intelligence (AI) concept for microcontrollers and sensors that contains a completely configurable artificial neural network</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.dailymail.co.uk/news/article-7102137/Professor-saw-Elizabeth-Holmes-explains-men-invested-Theranos-fraud.html">Stanford professor who saw through Elizabeth Holmes and her Theranos blood testing machine explains why so many men invested in the fraud</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.bbc.com/news/world-asia-china-48516455">Tiananmen 30<sup>th</sup> anniversary: Thousands hold huge vigil in Hong Kong</a><!--/html_preserve-->



# 05

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.tomshardware.com/news/amd-zen-china-x86-ip-license,39573.html">AMD not conducting further technology transfers of x86 IP to China JV</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.fifa.com/u20worldcup/news/sehun-heads-korea-republic-into-quarter-finals#korea-players-celebrate-victory">FIFA U-20 World Cup Poland 2019; Sehun heads Korea Republic into quarter-finals</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="http://www.aparchive.com/metadata/youtube/d4da8d0289a7ffb10059d367a2071f43">'Tank Man' statue unveiled at DC Tiananmem rally</a><!--/html_preserve-->


# 06

* <!--html_preserve--><a style="color: #1E6BB8;" href="http://www.koreaherald.com/view.php?ud=20190606000056">Memorial Day in South Korea; Moon urges national unity based on patriotism in Memorial Day speech</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.cbc.ca/sports/basketball/nba/toronto-raptors-golden-state-warriors-devin-heroux-game-4-1.5164335">Raptors' Game 3 win at Oracle Arena puts Warriors in uncharted territory</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.foxsportsasia.com/football/asian-football/1112528/watch-vietnam-players-celebrate-with-fans-after-defeating-thailand-to-reach-the-kings-cup-2019-final/">Vietnam players celebrate with fans after defeating Thailand to reach the King's Cup 2019 final</a><!--/html_preserve-->


# 07

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.nytimes.com/2019/06/07/sports/raptors-warriors-score.html">Raptors won Game 4 and are 1 win from an NBA Championship</a><!--/html_preserve-->



# 08

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.bbc.com/sport/football/48568240">Euro 2020 qualifiers: Turkey 2-0 France</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.fifa.com/u20worldcup/news/korea-republic-complete-thrilling-comeback-on-penalties#fans-of-korea-republic-show-their-support-x5055">FIFA U-20 World Cup Poland 2019; [Korea Republic 3-3 Senegal a.e.t., 3-2 penalties] Korea Republic complete thrilling comeback on penalties</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.fifa.com/womensworldcup/news/renard-heads-hosts-to-the-perfect-start#eugenie-le-sommer-of-france-celebrates-with-teammates-after-scoring-x2182">FIFA Women's World Cup France 2019; [France 4-0 Korea Republic] Hosts make the perfect start</a><!--/html_preserve-->




# 09

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.wsj.com/articles/china-warns-tech-companies-about-complying-with-trade-restrictions-11560024872">China warns tech companies about complying with trade restrictions</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.cnn.com/2019/06/08/asia/hong-kong-extradition-bill-protest-intl/index.html">More than 1 million protest in Hong Kong, organizers say, over Chinese extradition law</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.euronews.com/2019/06/09/portugal-win-inaugural-uefa-nations-league-tournament">Portugal win inaugural UEFA Nations League tournament</a><!--/html_preserve-->


# 10

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.nba.com/article/2019/06/10/durant-reinjures-calf">Durant suffers Achilles injury in Game 5 of Finals</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.theguardian.com/sport/live/2019/jun/10/nba-finals-game-5-golden-state-warriors-toronto-raptors-live-score">Golden State Warriors 106-105 Toronto Raptors: NBA finals Game 5</a><!--/html_preserve-->



# 11

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.fifa.com/u20worldcup/news/korea-republic-edge-ecuador-to-set-up-historic-final#a-detailed-shot-of-the-fifa-u-20-logo">FIFA U-20 World Cup Poland 2019; [Korea Republic 1:0 Ecuador] Korea Republic edge Ecuador to set up historic final</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.zdnet.com/article/programming-languages-python-predicted-to-overtake-c-and-java-in-next-4-years/">Programming languages: Python predicted to overtake C and Java in next 4 years</a><!--/html_preserve-->




# 12

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://wccftech.com/amd-ryzen-9-3950x-16-core-cpu-benchmark-leak-crushes-intel-core-i9-9980xe/">AMD Ryzen 9 3950X 16 Core CPU Benchmark leaks out, obliterates the Intel Core i9-9980XE 18 Core CPU in single and multi-threaded workloads</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.wsj.com/articles/huawei-cancels-launch-of-new-laptop-as-u-s-restrictions-sting-11560320526">Huawei cancels launch of new laptop as U.S. restrictions sting</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.soa.org/resources/announcements/press-releases/2019/naic-approves-soa-gi-track-for-qualified-actuary-education/">NAIC Approves SOA GI Track for Qualified Actuary Education</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.cicnews.com/2019/06/new-express-entry-draw-sees-cut-off-score-decrease-by-5-points-0612371.html#gs.ino6oa">New Express Entry draw sees cut-off score decrease by 5 points</a><!--/html_preserve-->


# 13

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.bloomberg.com/news/articles/2019-06-11/hon-hai-has-enough-ex-china-capacity-to-make-u-s-bound-products">Apple's U.S. iPhones can all be made outside of China if needed</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.bloomberg.com/news/articles/2019-06-12/u-s-tells-un-committee-north-korea-has-breached-oil-import-cap">North Korea has breached oil import limit, U.S. tells UN</a><!--/html_preserve-->


# 14


* <!--html_preserve--><a style="color: #1E6BB8;" href="https://globalnews.ca/video/5389585/nba-finals-toronto-raptors-presented-with-nba-championship-trophy">NBA Finals: Toronto Raptors presented with NBA championship trophy</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.itpro.co.uk/hardware/33837/windows-10-may-update-helps-ramp-up-amd-ryzen-performance">Windows 10 May update helps ramp up AMD Ryzen performance</a><!--/html_preserve-->


# 15

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.fifa.com/u20worldcup/news/spirited-comeback-earns-ukraine-first-u-20-title#ukraine-v-korea-republic-final-2019-fifa-u-20-world-cup-x8898">Spirited comeback earns Ukraine first U-20 title</a><!--/html_preserve-->


# 16

* <!--html_preserve--><a style="color: #1E6BB8;" href="http://www.donga.com/en/home/article/all/20190618/1764012/1/Ryu-Hyun-jin-misses-out-on-his-10th-win-of-the-season">Ryu Hyun-jin misses out on his 10th win of the season</a><!--/html_preserve-->


# 17

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.news.com.au/world/asia/multiple-deaths-and-injuries-in-china-earthquake/news-story/cd8c8c2c103d2abbf64994fabfdbc081">Multiple deaths and injuries in China earthquake</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.theguardian.com/football/live/2019/jun/17/south-korea-v-norway-nigeria-v-france-womens-world-cup-clockwatch-live">Nigeria 0-1 France, South Korea 1-2 Norway</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.washingtonpost.com/weather/2019/06/14/arctic-ocean-greenland-ice-sheet-have-seen-record-june-ice-loss/?noredirect=on&utm_source=pocket-newtab&utm_term=.de793208a5ba">Temperatures leap 40 degrees above normal as the Arctic Ocean and Greenland ice sheet see record June melting</a><!--/html_preserve-->



# 18

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.thestar.com/news/gta/2019/06/18/ttc-hits-pause-on-relief-line-work-amid-provincial-transit-plans.html">TTC hits pause on relief line work amid provincial transit plans</a><!--/html_preserve-->

# 19

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.sport-english.com/en/news/futbol-internacional/fifa-are-considering-whether-to-move-the-2022-world-cup-away-from-qatar-7512769">FIFA are considering whether to move the 2022 World Cup away from Qatar</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.dualshockers.com/god-of-war-sequel-sony-hiring-people-with-knowledge-of-god-of-war/">God of War sequel seems to be in the works as Sony begins hiring people with "Knowledge of God of War"</a><!--/html_preserve--> 
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.cbc.ca/news/canada/toronto/raptors-parade-stabbing-suspect-images-1.5181040">Police release images of man wanted for stabbings at Raptors' victory parade</a><!--/html_preserve-->



# 20

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.ctvnews.ca/politics/trump-offers-help-with-canadian-detainees-in-china-in-upbeat-visit-with-trudeau-1.4474481">Trump offers help with Canadian detainees in China in upbeat visit with Trudeau</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.sciencedaily.com/releases/2019/06/190618123509.htm">Two new Earth-like planets discovered near Teegarden's Star</a><!--/html_preserve-->

# 21


* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.ctvnews.ca/canada/desjardins-says-info-for-2-9m-members-shared-outside-of-organization-1.4475253">Desjardins says info for 2.9M members shared outside of organization</a><!--/html_preserve-->


# 22

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.bbc.co.uk/bbcthree/article/68c9c99d-c9d8-4857-96dd-b10336e2118e">"Leeds season": one of the weirdest footballing terms from around the world</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.howtogeek.com/426068/steam-wont-support-ubuntu-19.10-and-future-releases/">Steam won't support Ubuntu 19.10 and future releases</a><!--/html_preserve-->

# 23

* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.cbc.ca/news/canada/toronto/air-canada-sleeping-passenger-1.5186858">Air Canada reviewing how crew left sleeping passenger on plane</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.tellerreport.com/sports/2019-06-23---the-first-three-runs-on-defensive-errors------ryu-hyun-jin--another-failed--10-wins--.ryeQOFgakB.html">The first three runs on defensive errors... Ryu Hyun-jin, another failed '10 wins'</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.dexerto.com/entertainment/youtuber-claims-lost-job-videos-pewdiepie-743397">YouTuber claims he lost his job over videos about PewDiePie</a><!--/html_preserve-->

# 24

* <!--html_preserve--><a style="color: #1E6BB8;" href="http://www.sportbible.com/football/reactions-news-take-a-bow-k-league-side-gangwon-fc-produce-the-greatest-comeback-of-all-time-20190623">From 0:4 to 5:4, K-League side Gangwon FC produce the greatest comeback of all time</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.straitstimes.com/asia/east-asia/magnitude-55-quake-hits-eastern-japan-no-immediate-damage">Magnitude 5.5 quake hits eastern Japan, no immediate damage</a><!--/html_preserve-->
* <!--html_preserve--><a style="color: #1E6BB8;" href="https://www.gizmodo.co.uk/2019/06/teen-has-mouth-wired-shut-after-vape-explodes-fracturing-his-jaw-and-knocking-out-teeth/">Teen has mouth wired shut after vape explodes, fracturing his jaw and knocking out Teeth</a><!--/html_preserve-->


# 25
# 26
# 27
# 28
# 29
# 30









