---
title: "Binarizing data using `data.table`"
header-includes:
 - \usepackage{cancel}
 - \newcommand{\bX}{\mathbf{X}}
 - \newcommand{\bx}{\mathbf{x}}
 - \newcommand{\bY}{\mathbf{Y}}
author: Junkyu Park
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    includes:
      in_header: 
        - ../../style/all_ga_script.html
        - ../../style/all_navbar_head.html
        - ../../style/all_orange_jp_02_lvl.html
      before_body:
        - ../../style/all_navbar_body_02_lvl.html
      after_body:
        - ../../style/all_footer_02_lvl.html
    toc: FALSE
    self_contained: FALSE
---

The following packages and datasets are used:

```{r loading, warning = F, message = F}
library(data.table)
library(pROC)
data(nodal, package = 'SMPracticals')
data(smoking, package = 'SMPracticals')
```

<!--html_preserve-->
<div id="TOC" class="toc" style="padding:2rem 2rem 0 0;">
<ul style="list-style:none;">
<li><a href="#introduction">1. Introduction</a></li>
<li><a href="#case-studies">2. Case studies</a><ul>
<li><a href="#case-1-nodal">Case 1: <code>nodal</code></a></li>
<li><a href="#case-2-smoking">Case 2: <code>smoking</code></a></li>
</ul></li>
<li><a href="#session-info">Session info</a></li>
</ul>
</div>
&nbsp;
<!--/html_preserve-->


# 1. Introduction




# 2. Case studies

## Case 1: `nodal`


## Case 2: `smoking`






# Session info

R session info:

```{r session_info}
sessionInfo()
```





