---
title: "Research materials: 2018"
header-includes:
 - \usepackage{cancel}
 - \newcommand{\bX}{\mathbf{X}}
 - \newcommand{\bx}{\mathbf{x}}
 - \newcommand{\bY}{\mathbf{Y}}
author: Junkyu Park
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    includes:
      in_header: 
        - ../style/all_ga_script.html
        - ../style/all_navbar_head.html
        - ../style/all_orange_jp_01_lvl.html
      before_body:
        - ../style/all_navbar_body_01_lvl.html
      after_body:
        - ../style/all_footer_01_lvl.html
    self_contained: FALSE
---

# Methods of Applied Statistics

* Binarization of data using `data.table` in R
* [Censored data](2018/censored_data.html)
* Linear mixed effects model
* [Visualizing confidence regions](2018/visualizing_confidence_regions.html)



# Ordinary Differential Equations

* Visualizing Mankiw-Romer-Weil growth model


<!-- ## Probability -->

<!-- (01) Randomness -->
<!-- (02) Probability and functions -->
<!-- (03) Bernoulli and beyond -->
<!-- (04) Gamma and beyond -->
<!-- (05) Normal and beyond -->
<!-- (06) Conditional expectations -->
<!-- (07) Towards multivariate cases -->
<!-- (08) Dirichlet and more -->
<!-- (09) Characteristic functions -->
<!-- (10) Multivariate normal -->
<!-- (11) Rotational invariance -->


# Statistical Computation

* Boundary estimation
* [Dealing with a non-separable penalty term](2018/non_separable_penalty.html)
* [Evaluating a hard-to-evaluate pmf using pgf and DFT](2018/pgf.html)
* [Using pgf and DFT: Python implementation](2018/pgf_python.html)


# Time Series Analysis

* [Study note 1: weak stationarity, ARIMA, Dickey-Fuller](../files/study_note1.pdf)
* [Study note 2: TFNM](../files/study_note2.pdf)
* [Study note 3: VAR, Granger causality, cointegration, multivariate times series](../files/study_note3.pdf)
* [Study note 4: state-space model, bootstrap](../files/study_note4.pdf)
* [Study note 5: problems, summary](../files/study_note5.pdf)

<!-- 1. Weak stationarity -->
<!--     + Functions: mean, variance, AVCF, ACF, and CCF -->
<!--     + Definition of weak stationarity -->
<!--     + PACF -->
<!--     + White noise -->
<!-- 2. Modeling -->
<!--     + Decomposition of time series -->
<!--     + Steps to time series modeling -->
<!--     + Three stages of Box-Jenkins Approach -->
<!--     + $\text{ARMA}(p, q)$ -->
<!--         + Wold decomposition -->
<!--         + $\text{AR}(p)$ -->
<!--         + $\text{MA}(q)$ -->
<!--         + Causal and invertible processes -->
<!--         + $\text{ARMA}(p, q)$ -->
<!--     + Diagnostics -->
<!--         + Portmanteau tests -->
<!--     + Model selection -->
<!--     + $\text{ARIMA}(p, d, q)$ -->
<!--         + $I(d)$ and Dickey-Fuller test -->
<!--         + Selection of $p$, the lag length -->
<!-- 3. TFNM -->
<!-- 4. Vector autoregression -->
<!-- 5. Granger causality -->
<!-- 6. Cointergration -->
<!--     + Definition -->
<!--     + Error correction model -->
<!--     + Granger representation theorem -->
<!--     + The procedure of Engle and Granger (1987) -->
<!--     + An example: pairs trading -->
<!-- 7. Multivariate times series -->
<!-- 8. State-space model -->

