<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Junkyu Park" />


<title>sudsoln: analysis</title>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-139050237-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-139050237-1');
</script>
<!-- A new navigation bar style settings -->
<style type="text/css">
/* at the top */
#navbar
{
    position: sticky;
    z-index: 1000; /* new; why: make navbar closest to the observer */
    top: 0;
    left: 0;
    padding: 0; /* old: 10px 25px */
    background: rgba(28, 44, 56, 0.99);
    width: 100%;
    height: 50px;
    box-sizing: border-box;
    border-bottom: 1px solid #EAEAEB;
    transition: .5s;
}
#navbar .logo
{
    float: left;
}
#navbar .logo img
{
    height: 30px;
    /* new: margin; why: so that in header, padding can be 0 */
    /* note: header nav ul li a has margin 20px on left and right, 
    so here I let the right margin of img to be 5px so that it matches
    with the left margin 25px */
    /* edit: 5 to 20px since it looks nicer */
    margin: 10px 20px 10px 25px; 
}
#navbar nav
{
    float: right; /* old: left; why change: to give a more standard look */
    margin: 0 27.5px 0 0;
}
#navbar nav ul
{
    margin: 0;
    padding: 0;
    display: flex;

}
#navbar nav ul li
{
    padding: 0;
    list-style: none;
    position: relative;
    /* new: margin and padding; why: header padding is now 0 */
    margin: 0;
    padding: 8.5px 0 8.5px 0;
}
/* new; why: texts with arrow on the right gets more space  */
#navbar nav ul li.sub-menu
{
    /* why 8.5px: that's the value in header nav ul li padding */
    padding: 8.5px 27.5px 8.5px 0;
    padding-bottom: 12px;
    /* new; why: to make dropdown menu available once the mouse is on the menu item that it belongs, and to not affect other menu items that is not of class sub-menu */
}

/* new; why: prepare in case of text-align: right */
/* commented out because news menu is now gone in navbar*/
/* #navbar nav ul li#news
{
    padding: 8.5px 0;
    margin: 0;
} */

/* new; why: this potentially has a different background color */
#navbar nav ul li#home
{
    background-color: rgba(21, 92, 148, .9); /* old: rgba(28, 44, 56, 0); */
    border-bottom: 1px solid #EAEAEB;
    margin: 0 0 .5px 0;
}

#navbar nav ul li.sub-menu:before
{
    content: '\f0d7'; /* &#9660 ▼ nabla */
    font-family: fontAwesome; /* old: sans-serif */
    font-size: 16pt;
    position: absolute;
    /*line-height: 30px;*/
    color: #ffffff;
    top: 7pt;
    right: 22.5px;
    cursor: pointer;
}
#navbar nav ul li.active.sub-menu:before
{
    content: '\f0d8';  /* &#9650 ▲ Delta */
    font-family: fontAwesome; /* new */
    font-size: 16pt;
    position: absolute;
    color: #666;
    top: 7pt;
    right: 22.5px;
    cursor: pointer;
}
#navbar nav ul li ul
{
    position: absolute;
    left: 0;
    top: 50px; /* controls the box position of dropdown menus */
    background: rgba(57, 143, 209, 0.99);
    display: none;
}
#navbar nav ul li.active ul
{
    display: block;
}

/* new; why: make dropdown menu box fit to the menu above */
/* padding: 0; is for slimmer individual dropdown menu items */
/* old */
#navbar nav ul li.sub-menu ul li
{
    display: block;
    width: 200px;
    padding: 5px 0;
}

/* new: header nav ul li ul li a */
/* why: giving an indentation */
#navbar nav ul li ul li a
{
    margin: 0 40px;
}

/* header nav ul li#projects.sub-menu ul li
{
    display: block;
    width: 115px;
    padding: 0;
}
header nav ul li#rm.sub-menu ul li
{
    display: block;
    width: 197px;
    padding: 0;
} */

#navbar nav ul li a
{
    height: 30px;
    line-height: 30px;
    padding: 0; /* old: 0 20px, and margin didn't exist; why change: to make text the only clickable object */
    margin: 0 20px;
    color: #ffffff;
    text-decoration: none;
    text-shadow: none; /* new; why: to be compatible with the Tactile theme */
    /*display: block;*/
}

/* new: news; why add: to make News go to the right */
/* commented out because the same effect is achieved by having 
header nav ul li.sub-menu padding: 8.5px 15px 8.5px 0; */
/* header nav ul li.news
{
    margin: 0 0 0 20px;
} */

/* new: rm; why: to make r_m go to the right */
/* commented out because the same effect is achieved by having 
header nav ul li.sub-menu padding: 8.5px 15px 8.5px 0; */
/* header nav ul li#rm
{
    margin: 0 0 0 20px;
} */


#navbar nav ul li a:hover
{
    color: #666;
}

/* new: header nav ul li:hover ul, why: to make dropdown menu appear whenever mouse is above */
#navbar nav ul li:hover ul
{
    display: block;
}

#navbar nav ul li:hover ul li:hover
{
    background-color: rgba(5, 83, 143, 0.99);
}

.menu-toggle
{
    color: #ffffff;
    float: right;
    line-height: 30px;
    font-size: 24px;
    cursor: pointer;
    display: none;
    text-shadow: none;
}
@media (max-width: 800px) /* old1: 991px; old2: 721px */
{
    /* at the top */
    #navbar
    {
        padding: 0; /* old: 10px 25px */
    }
    .menu-toggle
    {
        display: block;
        margin: 10px 25px /* new; why: header padding is now 0 */
    }
    #navbar nav
    {
        /*display: none;*/
        overflow: auto; /* new; why: when mobile, make sure scroll shows up if vertical space not sufficient to display every element of nav */
        position: absolute;
        width: 100%;
        height: calc(100vh - 50px);
        background: rgba(28, 44, 56, 0.99);
        top: 50px;
        left: -100%;
        transition: .5s;
    }
    #navbar nav.active
    {
        left: 0;
    }
    #navbar nav ul
    {
        display: block;
        /*text-align: center;*/
    }

    /* new; why: to make sure it doesn't appear in mobile view;
    I don't want to see it in mobile since the logo already directs you
    to home. Adding home in mobile seems a clutter.
    */
    #navbar nav ul li#home
    {
        display: none;
    }

    #navbar nav ul li a
    {
        border-bottom: 1px solid rgba(255, 255, 255, .5);
        height: 50px;
        line-height: 50px;
        padding: 0 20px;
    }
    #navbar nav ul li.active ul
    {
        position: relative;
    }
    #navbar nav ul li ul li
    {
        width: 100%;
    }

    /* new: header nav ul li.sub-menu */
    /* why: so that dropdown menus fill the entire row in mobile */
    #navbar nav ul li.sub-menu
    {
        padding: 8.5px 0;
    }

    #navbar nav ul li.sub-menu:before
    {
        content: '+'; /* old: &#9660 nabla */
        font-size: 20pt;
        font-family: sans-serif;
        height: 40px;
        position: absolute;
        /* line-height: 30px; */
        color: #ffffff;
        width: 20px;
        /* top: 5pt; */
        right: 25px;
        cursor: pointer;
        bottom: 18px;
    }
    #navbar nav ul li.active.sub-menu:before
    {
        content: '–';  /* new: &#9650 Delta */
        font-size: 20pt;
        /* top: 5pt; */
        right: 25px;
        /* line-height: 30px; */
        cursor: pointer;
        position: absolute;
        color: #666;
        bottom: 18px;
        height: 40px;
    }
    #navbar nav ul li ul
    {
        position: absolute;
        left: 0;
        top: 0px; /* controls the box position of 2018 and 2019 under Research materials */
        background: rgba(57, 143, 209, 0.99);
        display: none;
    }

    /* new: hover and active
    why: do not display drop down menus when mouse is over it in mobile, 
    but display them when plus signs are clicked */
    #navbar nav ul li:hover ul
    {
        display: none;
    }
    #navbar nav ul li.active ul
    {
        display: block;
    }

    /* new; why: no background color change in dropdown menu when hovering over in mobile */
    #navbar nav ul li.sub-menu:hover ul li:hover
    {
        background-color: rgba(5, 83, 143, 0);
    }

    /* new: News; why: to make News align with the others in mobile */
    /* commented out since Research Materials uses different method
    to get more space on its right (header nav ul li.sub-menu padding) */

    /* header nav ul li.news
    {
        margin: 0;
    } */
    /* new: rm; why: to make rm align with the others in mobile */
    /* commented out for the same reason */
    /* header nav ul li#rm
    {
        margin: 0;
    } */

    /* while scrolling */
    #navbar.black nav ul li a:hover
    {
        color: #666;
    }
}

/* while scrolling */
#navbar.black
{
    background: rgba(21, 92, 148, .9);
}
#navbar.black nav ul li#home
{
    background-color: rgba(28, 44, 56, 0);
    /* border-bottom: 1px solid #EAEAEB;
    margin: 0 0 .5px 0; why commented: unnecessary */
    transition: .2s;
}
#navbar.black nav ul li a:hover
{
    color: darkgrey;
}
#navbar.black nav ul li.active.sub-menu:before
{
    color: darkgrey;
}
</style>

<!-- 1. Navigation bar color change as one scrolls -->
<!-- by adding a new class="black" while scrolling -->
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript">
    $(window).on('scroll', function(){
        if ($(window).scrollTop()){
           navbar.classList.add('black');
           /* old: $('header').addClass('black'); */
        }
        else
        {
            navbar.classList.remove('black');
            /* old: $('header').removeClass('black'); */
        }
    })
</script>

<!-- 2. Navigation bar slides from the left in mobile -->
<!-- 3. Only one dropdown menu at a time will appear -->
<script type="text/javascript">
    $(document).ready(function(){
        $('.menu-toggle').click(function(){
            $('nav').toggleClass('active')
        })
        $('ul li').click(function(){
            $(this).siblings().removeClass('active');
            $(this).toggleClass('active');
        })
    })
</script>

<!-- Using caret down and up symbols -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link rel="icon" href="../../../style/all_orange_jp.png">


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<link rel="stylesheet" href="analysis_files/style.css" type="text/css" />





</head>

<body>


<!-- A new navigation bar -->
<div id="navbar">
    <div class="logo">
        <a href="../../../index.html"><img src="../../../style/all_orange_jp.png"></a>
    </div>
    <nav>
        <ul>
            <li id="home">
                <a href="../../../index.html">Home</a>
            </li>
            <li class="sub-menu" id="projects">
                <a href="../../../projects.html">Projects</a>
                <ul>
                    <li>
                        <a href="../../../projects/2019.html">2019</a>
                    </li>
                </ul>
            </li>
            <li class="sub-menu" id="rm">
                <a href="../../../research_materials.html">Research materials</a>
                <ul>
                    <li>
                        <a href="../../../research_materials/2018.html">2018</a>
                    </li>
                    <li>
                        <a href="../../../research_materials/2019.html">2019</a>
                    </li>
                </ul>
            </li>
            <!-- <li id="news">
                <a href="../../../news.html">News</a>
            </li> -->
            <li>
                <a href="../../../files/resume_junkyu_park.pdf">Resume</a>
            </li>
        </ul>
    </nav>
    <div class="menu-toggle">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
</div>


<section class="page-header">
<h1 class="title toc-ignore project-name">sudsoln: analysis</h1>
<h4 class="author project-author">Junkyu Park</h4>
</section>



<section class="main-content">
<p>The following packages are used for analysis:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb1-1" title="1"><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</a>
<a class="sourceLine" id="cb1-2" title="2"><span class="im">import</span> numpy <span class="im">as</span> np</a>
<a class="sourceLine" id="cb1-3" title="3"><span class="im">import</span> pandas <span class="im">as</span> pd</a>
<a class="sourceLine" id="cb1-4" title="4"><span class="im">import</span> random</a>
<a class="sourceLine" id="cb1-5" title="5"><span class="im">import</span> sudsoln <span class="im">as</span> ss</a></code></pre></div>
<p><code>sudsoln.Sudoku.solve()</code> method is used to solve <a href="https://norvig.com/top95.txt">95 hard</a> questions and <a href="https://norvig.com/hardest.txt">11 hardest</a> questions posted on Dr. Peter Norvig’s <a href="https://norvig.com/sudoku.html">website</a>.</p>

<div id="TOC" class="toc" style="padding:2rem 2rem 0 0;">
<ul style="list-style:none;">
<li><a href="#results">1. Results</a></li>
<li><a href="#analysis">2. Analysis</a><ul>
<li><a href="#how-long-did-it-take-to-solve-a-puzzle">2.1. How long did it take to solve a puzzle?</a></li>
<li><a href="#how-many-puzzles-required-a-brute-force-to-be-solved">2.2. How many puzzles required a brute force to be solved?</a></li>
<li><a href="#how-many-attempts-did-it-take-to-solve-a-puzzle-if-forcefully-solved">2.3. How many attempts did it take to solve a puzzle if forcefully solved?</a></li>
</ul></li>
<li><a href="#session-info">Session info</a></li>
</ul>
</div>
&nbsp;

<div id="results" class="section level1">
<h1>1. Results</h1>
<p>You can run the following <a href="../../../files/sudsoln_solving.py">script</a> to create <a href="../../../files/result_sudsoln0.1.0.csv">result_sudsoln0.1.0.csv</a> file, and then this <a href="../../../files/sudsoln_produce_results.py">script</a> to produce tables used in analysis. <code>time</code>s are in seconds:</p>
<pre><code>##           is_solved  total  min_time  median_time   avg_time    max_time
## category                                                                
## top95            92     95  0.191515     3.739001  18.551033  203.363059
## hardest           9     11  0.048868     1.840078  28.375194  176.589680
## all             101    106  0.048868     3.616845  19.570521  203.363059</code></pre>
<p>Note that:</p>
<ol style="list-style-type: decimal">
<li>101 out of 106 are solved, which results in a solving rate of 95.283%. I’m hoping to achieve 100% solution rate in future updates by incorporating more logical approaches and adapting a better search algorithm.</li>
<li><code>time</code>s are extremely right-skewed in every <code>category</code>. See <a href="#how-many-attempts-did-it-take-to-solve-a-puzzle-if-forcefully-solved">section 2.3.</a> below for details.</li>
</ol>
</div>
<div id="analysis" class="section level1">
<h1>2. Analysis</h1>
<div id="how-long-did-it-take-to-solve-a-puzzle" class="section level2">
<h2>2.1. How long did it take to solve a puzzle?</h2>
<p><code>time</code>s displayed in the table above show how long <code>ss.Sudoku.solve()</code> ran most of the time, NOT how long it took to solve a puzzle. To see how long the method ran most of the time <em>given that it solved a puzzle</em>, a grouping by <code>is_solved</code> column is required:</p>
<pre><code>##                     total    min_time  median_time    avg_time    max_time
## category is_solved                                                        
## top95    True          92    0.191515     3.665694   15.002534  203.363059
##          False          3  104.997169   116.626084  127.371666  160.491744
## hardest  True           9    0.048868     0.741012    2.162101   10.310423
##          False          2  116.078541   146.334111  146.334111  176.589680
## all      True         101    0.048868     3.557485   13.858337  203.363059
##          False          5  104.997169   116.626084  134.956644  176.589680</code></pre>
<p>In terms of times consumed, it is hard to say there is a difference in terms of difficulty between puzzles in <code>top95</code> category and <code>hardest</code> category. One reason for this is because there are only 11 puzzles in <code>hardest</code>. It is true that every solved puzzles in <code>hardest</code> category are solved in 10.31 seconds, which is less than the average time (15.003 seconds) consumed by solved puzzles in <code>top95</code> category, and one might say puzzles in <code>hardest</code> are actually easier than <code>top95</code> counterparts. However, <code>top95</code> has 95 puzzles which makes it more prone to having outliers. <code>hardest</code> doesn’t have enough puzzles to comment about their nature. Also, the mean time consumed to solve <code>hardest</code> puzzles is 2.162 seconds, which is close to 3.666 seconds, the median time consumed by solved puzzles of <code>top95</code> category. This implies that solved puzzles in <code>hardest</code> and <code>top95</code> are quite similar in nature.</p>
</div>
<div id="how-many-puzzles-required-a-brute-force-to-be-solved" class="section level2">
<h2>2.2. How many puzzles required a brute force to be solved?</h2>
<pre><code>##             total    min_time  median_time    avg_time    max_time
## solved                                                            
## logically      18    0.048868     0.415899    0.356829    0.631310
## forcefully     83    0.370045     5.146216   16.786375  203.363059
## not_solved      5  104.997169   116.626084  134.956644  176.589680</code></pre>
<p>Out of 101 solved puzzles, 18 puzzles (17.822%) were solved by logical approaches only, and 83 puzzles (82.178%) required a brute force.</p>
<p>It is not surprising to see that puzzles were solved significantly faster when they were solely solved by logical approaches. This is quite obvious because <code>ss.Sudoku.solve()</code> first uses <code>ss.Sudoku.solve_logically()</code> and then <code>ss.Sudoku.solve_forcefully()</code> if logical approaches aren’t enough. That is, every forcefully solved puzzle first went through <code>ss.Sudoku.solve_logically()</code> and then <code>ss.Sudoku.solve_forcefully()</code>.</p>
<p>Interestingly, the minimum time consumed by one of forcefully solved puzzles (0.37 seconds) is smaller than the maximum time consumed by one of logically solved puzzles (0.631 seconds), implying that there is a case where a forceful solving mechanism was actually faster than a logical reasoning. One explanation is that those puzzles become solvable by logic after plugging in one candidate value to an entry. A puzzle of this type makes <code>ss.Sudoku.solve_logically()</code> to return a fairly small <code>ss.candidate.Candidate</code>, so a single selection of candidate value in <code>ss.Sudoku.solve_forcefully()</code> immediately leads to the answer form (or one of possibly many answer forms).</p>
<pre><code>##    category      time  trial  is_solved
## 7     top95  0.565487      1       True
## 10    top95  0.589420      1       True
## 17    top95  0.426835      1       True
## 26    top95  0.589407      1       True
## 31    top95  0.370045      1       True
## 38    top95  0.484700      1       True
## 40    top95  0.546531      1       True
## 42    top95  0.505638      2       True
## 51    top95  0.501645      1       True
## 63    top95  0.468709      1       True</code></pre>
<p>The following table lists forcefully solved puzzles that took less than 0.631 seconds, the maximum time consumed by one of logically solved puzzles. Notice that <code>trial</code>s are either 1 or 2, indicating that after plugging in one or two values to the puzzle’s entries, <a href="https://joon3216.github.io/projects/2019/sudsoln/introduction.html#solve_forcefully">applying <code>ss.Sudoku.solve_logically()</code> inside <code>ss.Sudoku.solve_logically()</code></a> led to the answer.</p>
<pre><code>##     category      time  trial  is_solved
## 9      top95  1.269593      2       True
## 27     top95  0.766949      2       True
## 32     top95  1.883995      2       True
## 34     top95  0.738061      2       True
## 46     top95  0.838757      2       True
## 49     top95  0.702157      1       True
## 61     top95  1.067157      2       True
## 64     top95  1.738350      2       True
## 81     top95  1.537886      2       True
## 90     top95  0.669186      1       True
## 97   hardest  0.703121      1       True
## 104  hardest  0.741012      2       True</code></pre>
<p>This table shows forcefully solved puzzles that took longer than any other logically solved puzzles and yet took at most two attempts. We find that:</p>
<ol style="list-style-type: decimal">
<li>there are only 3 puzzles with <code>trial == 1</code> in this table, i.e. puzzles that took one attempt to solve are essentially the same as logically solved puzzles in terms of times consumed (They took no longer than 0.704 seconds). We may expect them to be solved completely by logic as the version increases.</li>
<li>puzzles solved within two attempts are all solved within 1.884 seconds.</li>
</ol>
</div>
<div id="how-many-attempts-did-it-take-to-solve-a-puzzle-if-forcefully-solved" class="section level2">
<h2>2.3. How many attempts did it take to solve a puzzle if forcefully solved?</h2>
<pre><code>##             total  min_trial  median_trial  avg_trial  max_trial
## solved                                                          
## forcefully     83          1             8  22.192771        196</code></pre>
<p>(<code>total</code> in the table is the number of cases out of 106 puzzles.)</p>
<p>The most apparent pattern is that both <code>time</code> and <code>trial</code> are extremely right-skewed regardless of the group. This shows that there is no “middle ground”, i.e. the package either solved a puzzle fairly quickly, or it took a very long time to solve one. Thus, the median is more reliable than the mean. According to the above table, about 8 trials are required whenever a puzzle requires a brute force to be solved.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb8-1" title="1"><span class="co"># Scatterplot: time vs. trial</span></a>
<a class="sourceLine" id="cb8-2" title="2">fig, ax <span class="op">=</span> plt.subplots()</a>
<a class="sourceLine" id="cb8-3" title="3"><span class="cf">for</span> solved_how <span class="kw">in</span> [<span class="st">&#39;logically&#39;</span>, <span class="st">&#39;forcefully&#39;</span>, <span class="st">&#39;not_solved&#39;</span>]:</a>
<a class="sourceLine" id="cb8-4" title="4">    ax.scatter(</a>
<a class="sourceLine" id="cb8-5" title="5">        x <span class="op">=</span> result_sudsoln.loc[<span class="kw">lambda</span> x: x[<span class="st">&#39;solved&#39;</span>] <span class="op">==</span> solved_how].trial,</a>
<a class="sourceLine" id="cb8-6" title="6">        y <span class="op">=</span> result_sudsoln.loc[<span class="kw">lambda</span> x: x[<span class="st">&#39;solved&#39;</span>] <span class="op">==</span> solved_how].time,</a>
<a class="sourceLine" id="cb8-7" title="7">        alpha <span class="op">=</span> <span class="fl">.2</span>,</a>
<a class="sourceLine" id="cb8-8" title="8">        label <span class="op">=</span> solved_how</a>
<a class="sourceLine" id="cb8-9" title="9">    )</a>
<a class="sourceLine" id="cb8-10" title="10">ax.legend(title <span class="op">=</span> <span class="st">&#39;How were they solved?&#39;</span>)</a>
<a class="sourceLine" id="cb8-11" title="11">ax.grid(<span class="va">True</span>)</a>
<a class="sourceLine" id="cb8-12" title="12">plt.xlabel(<span class="st">&#39;trial&#39;</span>)</a>
<a class="sourceLine" id="cb8-13" title="13">plt.ylabel(<span class="st">&#39;time (in sec)&#39;</span>)</a>
<a class="sourceLine" id="cb8-14" title="14">plt.title(<span class="st">&#39;Scatterplot of time vs. trial&#39;</span>)</a>
<a class="sourceLine" id="cb8-15" title="15">plt.show()</a></code></pre></div>
<p><img src="analysis_files/figure-html/scatter1-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The scatterplot of <code>time</code> vs. <code>trial</code> shows that the vast majority of puzzles are solved within 50 trials or about a minute. That is, setting a big <code>max_trial</code> in <code>ss.Sudoku.solve()</code> (which leads to a longer running time) will increase a chance of a puzzle getting solved, but not by a large scale after <code>max_trial</code> gets greater than 50.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb9-1" title="1"><span class="co"># Lineplot: prob vs. max_trial</span></a>
<a class="sourceLine" id="cb9-2" title="2">prob_vs_max_trial <span class="op">=</span> {<span class="st">&#39;max_trial&#39;</span>: [], <span class="st">&#39;prob&#39;</span>: []}</a>
<a class="sourceLine" id="cb9-3" title="3">numer <span class="op">=</span> result_sudsoln.shape[<span class="dv">0</span>]</a>
<a class="sourceLine" id="cb9-4" title="4"><span class="cf">for</span> attempt <span class="kw">in</span> <span class="bu">range</span>(max_trial <span class="op">+</span> <span class="dv">1</span>):</a>
<a class="sourceLine" id="cb9-5" title="5">    denom <span class="op">=</span> result_sudsoln<span class="op">\</span></a>
<a class="sourceLine" id="cb9-6" title="6">        .loc[<span class="kw">lambda</span> x: (x[<span class="st">&#39;trial&#39;</span>] <span class="op">&lt;=</span> attempt) <span class="op">&amp;</span> (x[<span class="st">&#39;is_solved&#39;</span>])]<span class="op">\</span></a>
<a class="sourceLine" id="cb9-7" title="7">        .total<span class="op">\</span></a>
<a class="sourceLine" id="cb9-8" title="8">        .<span class="bu">sum</span>()</a>
<a class="sourceLine" id="cb9-9" title="9">    prob_vs_max_trial[<span class="st">&#39;max_trial&#39;</span>].append(attempt)</a>
<a class="sourceLine" id="cb9-10" title="10">    prob_vs_max_trial[<span class="st">&#39;prob&#39;</span>].append(denom <span class="op">/</span> numer)</a>
<a class="sourceLine" id="cb9-11" title="11">prob_vs_max_trial <span class="op">=</span> pd.DataFrame(prob_vs_max_trial)</a>
<a class="sourceLine" id="cb9-12" title="12"></a>
<a class="sourceLine" id="cb9-13" title="13">plt.clf()</a>
<a class="sourceLine" id="cb9-14" title="14">plt.plot(prob_vs_max_trial.max_trial, prob_vs_max_trial.prob)</a>
<a class="sourceLine" id="cb9-15" title="15">plt.ylim(<span class="dv">0</span>, <span class="dv">1</span>) </a>
<a class="sourceLine" id="cb9-16" title="16">plt.yticks(np.arange(<span class="dv">0</span>, <span class="fl">1.1</span>, <span class="fl">.1</span>))</a>
<a class="sourceLine" id="cb9-17" title="17">plt.grid(<span class="va">True</span>)</a>
<a class="sourceLine" id="cb9-18" title="18">plt.xlabel(<span class="st">&#39;max_trial in ss.Sudoku.solve(max_trial)&#39;</span>)</a>
<a class="sourceLine" id="cb9-19" title="19">plt.ylabel(<span class="st">&#39;P(getting solved)&#39;</span>)</a>
<a class="sourceLine" id="cb9-20" title="20">plt.title(<span class="st">&#39;Expected P(getting solved) vs. max_trial&#39;</span>)</a>
<a class="sourceLine" id="cb9-21" title="21">plt.show()</a></code></pre></div>
<p><img src="analysis_files/figure-html/line1_real-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>This plot displays how the expected probability of a puzzle getting solved increases as <code>max_trial</code> argument specified in <code>ss.Sudoku.solve()</code> gets bigger. Notice the plateau starts after 50 <code>max_trial</code>, and stays around the probability of 90%.</p>
<p>To get the idea of how much more <code>time</code> is required as <code>trial</code> increases, I fit a linear regression model between log-transformed <code>time</code> and <code>trial</code>. In particular, the following model is used: <span class="math display">\[\log(\text{time}) = \beta_0 + \beta_1 \log(\text{trial} + 1) + \varepsilon\]</span> Log-transformations are performed due to a severe right-skewness on both the response and the feature; <code>trial + 1</code> is used because whenever <span class="math inline">\(\text{trial} = 0\)</span>, <span class="math inline">\(\log(\text{trial})\)</span> is undefined, and <span class="math inline">\(\log(\text{trial} + 1)\)</span> becomes exactly <span class="math inline">\(0\)</span>. Model-checking procedure is skipped, and the model is assumed to be appropriate to describe the relationship between the two.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb10-1" title="1"><span class="co"># Scatterplot: log(time) vs. log(trial + 1)</span></a>
<a class="sourceLine" id="cb10-2" title="2">X <span class="op">=</span> result_sudsoln.loc[:, [<span class="st">&#39;total&#39;</span>, <span class="st">&#39;trial&#39;</span>]]</a>
<a class="sourceLine" id="cb10-3" title="3">X.trial <span class="op">=</span> np.log(X.trial <span class="op">+</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb10-4" title="4">y <span class="op">=</span> result_sudsoln.loc[:, [<span class="st">&#39;time&#39;</span>]]</a>
<a class="sourceLine" id="cb10-5" title="5">y.time <span class="op">=</span> np.log(y.time)</a>
<a class="sourceLine" id="cb10-6" title="6">X, y <span class="op">=</span> X.values, y.values</a>
<a class="sourceLine" id="cb10-7" title="7">betas <span class="op">=</span> np.linalg.inv(X.T <span class="op">@</span> X) <span class="op">@</span> X.T <span class="op">@</span> y</a>
<a class="sourceLine" id="cb10-8" title="8">model_x <span class="op">=</span> np.linspace(<span class="dv">0</span>, np.<span class="bu">max</span>(X[:, <span class="dv">1</span>]))</a>
<a class="sourceLine" id="cb10-9" title="9">model_y <span class="op">=</span> betas[<span class="dv">0</span>] <span class="op">+</span> betas[<span class="dv">1</span>] <span class="op">*</span> model_x</a>
<a class="sourceLine" id="cb10-10" title="10"></a>
<a class="sourceLine" id="cb10-11" title="11">plt.clf()</a>
<a class="sourceLine" id="cb10-12" title="12">fig, ax <span class="op">=</span> plt.subplots()</a>
<a class="sourceLine" id="cb10-13" title="13"><span class="cf">for</span> solved_how <span class="kw">in</span> [<span class="st">&#39;logically&#39;</span>, <span class="st">&#39;forcefully&#39;</span>, <span class="st">&#39;not_solved&#39;</span>]:</a>
<a class="sourceLine" id="cb10-14" title="14">    ax.scatter(</a>
<a class="sourceLine" id="cb10-15" title="15">        x <span class="op">=</span> np.log(</a>
<a class="sourceLine" id="cb10-16" title="16">            result_sudsoln.loc[<span class="kw">lambda</span> x: x[<span class="st">&#39;solved&#39;</span>] <span class="op">==</span> solved_how].trial <span class="op">+</span> <span class="dv">1</span></a>
<a class="sourceLine" id="cb10-17" title="17">        ),</a>
<a class="sourceLine" id="cb10-18" title="18">        y <span class="op">=</span> np.log(</a>
<a class="sourceLine" id="cb10-19" title="19">            result_sudsoln.loc[<span class="kw">lambda</span> x: x[<span class="st">&#39;solved&#39;</span>] <span class="op">==</span> solved_how].time</a>
<a class="sourceLine" id="cb10-20" title="20">        ),</a>
<a class="sourceLine" id="cb10-21" title="21">        alpha <span class="op">=</span> <span class="fl">.2</span>,</a>
<a class="sourceLine" id="cb10-22" title="22">        label <span class="op">=</span> solved_how</a>
<a class="sourceLine" id="cb10-23" title="23">    )</a>
<a class="sourceLine" id="cb10-24" title="24">ax.legend(title <span class="op">=</span> <span class="st">&#39;How were they solved?&#39;</span>)</a>
<a class="sourceLine" id="cb10-25" title="25">ax.grid(<span class="va">True</span>)</a>
<a class="sourceLine" id="cb10-26" title="26">plt.plot(model_x, model_y, alpha <span class="op">=</span> <span class="fl">.5</span>)</a>
<a class="sourceLine" id="cb10-27" title="27">plt.xlabel(<span class="st">&#39;log(trial + 1)&#39;</span>)</a>
<a class="sourceLine" id="cb10-28" title="28">plt.ylabel(<span class="st">&#39;log(time)&#39;</span>)</a>
<a class="sourceLine" id="cb10-29" title="29">plt.title(<span class="st">&#39;Scatterplot of log(time) vs. log(trial + 1)&#39;</span>)</a>
<a class="sourceLine" id="cb10-30" title="30">plt.show()</a></code></pre></div>
<p><img src="analysis_files/figure-html/scatter2-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Although I didn’t check whether the model is appropriate, the regression line fits nicely in the scatterplot of <code>log(time)</code> vs. <code>log(trial + 1)</code>. It seems we don’t need to implement a nonlinear model, and need to deal with a fanning effect only.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb11-1" title="1"><span class="co"># time vs. trial according to the fitted model</span></a>
<a class="sourceLine" id="cb11-2" title="2">model_time <span class="op">=</span> <span class="kw">lambda</span> x: np.exp(betas[<span class="dv">0</span>] <span class="op">+</span> betas[<span class="dv">1</span>] <span class="op">*</span> np.log(x <span class="op">+</span> <span class="dv">1</span>))</a>
<a class="sourceLine" id="cb11-3" title="3">model_trials <span class="op">=</span> np.arange(<span class="dv">201</span>)</a>
<a class="sourceLine" id="cb11-4" title="4">model_times <span class="op">=</span> model_time(model_trials)</a>
<a class="sourceLine" id="cb11-5" title="5"></a>
<a class="sourceLine" id="cb11-6" title="6">plt.clf()</a>
<a class="sourceLine" id="cb11-7" title="7">fig, ax <span class="op">=</span> plt.subplots()</a>
<a class="sourceLine" id="cb11-8" title="8"><span class="cf">for</span> solved_how <span class="kw">in</span> [<span class="st">&#39;logically&#39;</span>, <span class="st">&#39;forcefully&#39;</span>, <span class="st">&#39;not_solved&#39;</span>]:</a>
<a class="sourceLine" id="cb11-9" title="9">    ax.scatter(</a>
<a class="sourceLine" id="cb11-10" title="10">        x <span class="op">=</span> result_sudsoln.loc[<span class="kw">lambda</span> x: x[<span class="st">&#39;solved&#39;</span>] <span class="op">==</span> solved_how].trial,</a>
<a class="sourceLine" id="cb11-11" title="11">        y <span class="op">=</span> result_sudsoln.loc[<span class="kw">lambda</span> x: x[<span class="st">&#39;solved&#39;</span>] <span class="op">==</span> solved_how].time,</a>
<a class="sourceLine" id="cb11-12" title="12">        alpha <span class="op">=</span> <span class="fl">.2</span>,</a>
<a class="sourceLine" id="cb11-13" title="13">        label <span class="op">=</span> solved_how</a>
<a class="sourceLine" id="cb11-14" title="14">    )</a>
<a class="sourceLine" id="cb11-15" title="15">ax.legend(title <span class="op">=</span> <span class="st">&#39;How were they solved?&#39;</span>)</a>
<a class="sourceLine" id="cb11-16" title="16">ax.grid(<span class="va">True</span>)</a>
<a class="sourceLine" id="cb11-17" title="17">plt.xlabel(<span class="st">&#39;trial&#39;</span>)</a>
<a class="sourceLine" id="cb11-18" title="18">plt.ylabel(<span class="st">&#39;time (in sec)&#39;</span>)</a>
<a class="sourceLine" id="cb11-19" title="19">plt.title(<span class="st">&#39;Scatterplot of time vs. trial with a regression line&#39;</span>)</a>
<a class="sourceLine" id="cb11-20" title="20">plt.plot(model_trials, model_times, alpha <span class="op">=</span> <span class="fl">.5</span>)</a>
<a class="sourceLine" id="cb11-21" title="21">plt.show()</a></code></pre></div>
<p><img src="analysis_files/figure-html/scatter3_real-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>According to the model:</p>
<ul>
<li>around 20% of sudoku puzzles with a <code>top95</code> or <code>hardest</code> difficulty are expected to be solved by <code>ss.Sudoku.solve_logically()</code> in about 0.326 seconds</li>
<li>around 90% of sudoku puzzles with a <code>top95</code> or <code>hardest</code> difficulty are expected to be solved by <code>ss.Sudoku.solve()</code> in about 50 attempts (trials), or 33.483 seconds</li>
<li><code>ss.Sudoku.solve()</code> is expected to terminate in about 168.522 seconds, regardless of whether the method solves a puzzle or not, if used the default setting of <code>max_trial = 200</code></li>
</ul>
</div>
</div>
<div id="session-info" class="section level1">
<h1>Session info</h1>
<div class="sourceCode" id="cb12"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb12-1" title="1"><span class="im">import</span> sinfo <span class="co"># ver 0.1.4</span></a>
<a class="sourceLine" id="cb12-2" title="2">sinfo.sinfo()</a></code></pre></div>
<pre><code>## -----
## matplotlib   3.1.1
## numpy        1.17.0
## pandas       0.25.0
## sudsoln      0.1.0
## -----
## Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
## Windows-10-10.0.18362-SP0
## 4 logical CPU cores, Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
## -----
## Session information updated at 2019-08-21 15:49</code></pre>
</div>
</section>

<!-- Footer -->
<!-- Reference: https://holtzy.github.io/Pimp-my-rmd/ -->
&nbsp; <!-- whitespace -->
<hr /> <!-- line -->
<div class="footer">
    <p style="text-align: center;">
        <a href="../../../index.html" style="font-size: 11pt;">Home</a> · <a href="../../../projects.html" style="font-size: 11pt;">Projects</a> · <a href="../../../research_materials.html" style="font-size: 11pt;">Research materials</a> · <a href="../../../files/resume_junkyu_park.pdf" style="font-size: 11pt;">Resume</a>
    </p>
    <p style="text-align: center;">
        © 2019 Junkyu Park<br>Powered by the <a href="https://github.com/yixuan/prettydoc">prettydoc::html_pretty</a> engine<br>Current theme: modified <a href="https://github.com/jasonlong/cayman-theme">Cayman</a>
    </p>
            
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
            
    <!-- Add font awesome icons -->
    <p style="text-align: center;">
        <span style="color: #555555;"><em>joon3216@gmail.com</em></span>
        <br>
        <a href="https://www.facebook.com/asdfzxcvjkl1" class="fa fa-facebook"></a>
        <a href="https://github.com/joon3216" class="fa fa-github"></a>
        <a href="https://linkedin.com/in/asdfzxcvjkl1/" class="fa fa-linkedin"></a>
        <a href="https://twitter.com/joon3216" class="fa fa-twitter"></a>
    </p>
</div>
&nbsp; <!-- whitespace -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
